INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('dhurai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('dhurai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('dhurai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('dhurai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('dhurai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('dhurai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('dhurai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('dhurai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('dhurai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('dhurai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('dhurai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('dhurai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('dhurai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('dhurai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('dhurai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('dhurai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('dhurai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('dhurai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('dhurai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /signup
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py", line 17, in wrapper_func
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py", line 122, in signup
    Profile = Customerdata.objects.create(user=user,)
                                               ^^^^
UnboundLocalError: cannot access local variable 'user' where it is not associated with a value
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
ERROR:django.request:Internal Server Error: /signup
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py", line 17, in wrapper_func
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py", line 117, in signup
    user = User(username=username, email=email,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\base.py", line 565, in __init__
    raise TypeError(
TypeError: User() got unexpected keyword arguments: 'password1', 'password2'
ERROR:django.request:Internal Server Error: /signup
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py", line 17, in wrapper_func
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py", line 117, in signup
    user = User(username=username, email=email,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\base.py", line 565, in __init__
    raise TypeError(
TypeError: User() got unexpected keyword arguments: 'password1', 'password2'
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
ERROR:django.request:Internal Server Error: /signup
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
          ^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1062, "Duplicate entry '13' for key 'products_customerdata.User_id'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py", line 17, in wrapper_func
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py", line 127, in signup
    Profile = Customerdata_Model.objects.create(user=user,)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\base.py", line 863, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\base.py", line 1006, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\base.py", line 1047, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
          ^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry '13' for key 'products_customerdata.User_id'")
ERROR:django.request:Internal Server Error: /signup
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
          ^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1062, "Duplicate entry '14' for key 'products_customerdata.User_id'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py", line 17, in wrapper_func
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py", line 127, in signup
    Profile = Customerdata_Model.objects.create(user=user,)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\base.py", line 863, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\base.py", line 1006, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\base.py", line 1047, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
          ^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry '14' for key 'products_customerdata.User_id'")
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
WARNING:django.security.csrf:Forbidden (CSRF token from POST incorrect.): /signin
WARNING:django.security.csrf:Forbidden (CSRF token from POST incorrect.): /admin/login/
WARNING:django.security.csrf:Forbidden (CSRF token from POST incorrect.): /admin/login/
WARNING:django.security.csrf:Forbidden (CSRF token from POST incorrect.): /admin/login/
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
WARNING:django.security.csrf:Forbidden (CSRF token from POST incorrect.): /signin
WARNING:django.security.csrf:Forbidden (CSRF token from POST incorrect.): /signin
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
ERROR:django.request:Internal Server Error: /store/
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py", line 384, in store
    data = Order.objects.filter(~Q(customer_fk_startswith='ellaidhurai'))
                                 ^
NameError: name 'Q' is not defined
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
ERROR:django.request:Internal Server Error: /store/
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py", line 384, in store
    data = Order.objects.filter(~Q(customer_fk_startswith='ellaidhurai'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\sql\query.py", line 1388, in build_filter
    return self._add_q(
           ^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'customer_fk_startswith' into field. Choices are: CreatedDate, Product_fk, Product_fk_id, customer_fk, customer_fk_id, id, note, quantity, shippingaddress, status
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
ERROR:django.request:Internal Server Error: /store/
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py", line 385, in store
    data = Order.objects.filter(~Q(status='Pending')) | Q(status='Out for delivery')
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\query.py", line 464, in __or__
    self._check_operator_queryset(other, "|")
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\query.py", line 1952, in _check_operator_queryset
    if self.query.combinator or other.query.combinator:
                                ^^^^^^^^^^^
AttributeError: 'Q' object has no attribute 'query'
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\src\settings.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\src\settings.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\src\settings.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\src\settings.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\src\settings.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\urls.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\youtube.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\youtube.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\youtube.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\products\exercise.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
ERROR:django.request:Internal Server Error: /checkout/
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py", line 437, in checkout
    print(customer_orders.Product_fk.Price)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'Product_fk'
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\urls.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
ERROR:django.request:Internal Server Error: /store/
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py", line 386, in store
    print(data.Apple)
          ^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'Apple'
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
ERROR:django.request:Internal Server Error: /checkout/
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py", line 434, in checkout
    print(data.Email)
          ^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'Email'
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
ERROR:django.request:Internal Server Error: /checkout/
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py", line 434, in checkout
    print(data['ellaidhurai'])
          ~~~~^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\query.py", line 414, in __getitem__
    raise TypeError(
TypeError: QuerySet indices must be integers or slices, not str.
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
ERROR:django.request:Internal Server Error: /checkout/
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py", line 438, in checkout
    print(customer_orders[0].customer_fk.status)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Customerdata' object has no attribute 'status'
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
ERROR:django.request:Internal Server Error: /user
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py", line 49, in wrapper_func
    return redirect('')
           ^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
ERROR:django.request:Internal Server Error: /user
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py", line 49, in wrapper_func
    return redirect('')
           ^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
ERROR:django.request:Internal Server Error: /user
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py", line 49, in wrapper_func
    return redirect('unauthorized')
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'unauthorized' not found. 'unauthorized' is not a valid view function or pattern name.
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\src\urls.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\urls.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\src\urls.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\src\settings.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\src\settings.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\src\settings.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\src\settings.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\src\settings.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
WARNING:django.request:Not Found: /foo.js
WARNING:django.request:Not Found: /foo.js
WARNING:django.request:Not Found: /home.js
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /signup
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py", line 18, in wrapper_func
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py", line 136, in signup
    return render(request, "auth/signup.html", success)
                                               ^^^^^^^
UnboundLocalError: cannot access local variable 'success' where it is not associated with a value
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
ERROR:django.request:Internal Server Error: /signup
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py", line 18, in wrapper_func
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py", line 129, in signup
    success = 'user' + username + 'created successfully'
                       ^^^^^^^^
UnboundLocalError: cannot access local variable 'username' where it is not associated with a value
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
ERROR:django.request:Internal Server Error: /signup
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py", line 18, in wrapper_func
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py", line 129, in signup
    success = 'user' + user_model.username + 'created successfully'
                       ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'user_model' where it is not associated with a value
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
ERROR:django.request:Internal Server Error: /signup
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py", line 18, in wrapper_func
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py", line 136, in signup
    return render(request, "auth/signup.html")
                                              
UnboundLocalError: cannot access local variable 'success' where it is not associated with a value
ERROR:django.request:Internal Server Error: /signup
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py", line 18, in wrapper_func
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py", line 136, in signup
    return render(request, "auth/signup.html")
                                              
UnboundLocalError: cannot access local variable 'success' where it is not associated with a value
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
ERROR:django.request:Internal Server Error: /signup
Traceback (most recent call last):
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\decorators.py", line 18, in wrapper_func
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py", line 116, in signup
    new_profile = Customerdata_Model.objects.create(user=user_model, id_user = user_model.id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\query.py", line 669, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\env\Lib\site-packages\django\db\models\base.py", line 565, in __init__
    raise TypeError(
TypeError: Customerdata() got unexpected keyword arguments: 'id_user'
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:django.utils.autoreload:E:\WEB DEVELOPEMENT\PYTHON\AUTHENDICATION\src\myapp\views.py changed, reloading.
INFO:root:Ran with args: ('ellai', 25), and kwargs:{}
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
